### ISSUE TITLE
[12.0] Installation bug

### ISSUE THREAD

**Issue by marcos-mendez** [OpenEMS/odoo-openems#1]
Hello guys, congrats for the work. I checked your module and both with and without demo data i keep getting this error. Can you help me?

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading odoo-openems failed: file odoo-openems/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Found more than 10 errors and more than one error per 10 records, interrupted to avoid showing too many errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1269, in run
    result = request.env['ir.actions.server'].browse([action_id]).run()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 553, in run
    res = func(action, eval_context=eval_context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 444, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 373, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 350, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
ValueError: <class 'Exception'>: "Module loading odoo-openems failed: file odoo-openems/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.model_openems_edge' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.model_openems_edge_user_role' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.model_openems_openemsconfigupdate' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_production_lot' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.model_openems_setup_protocol_item' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'stock.model_stock_production_lot' in field 'Object'
No matching record found for external id 'openems.group_openems_manager' in field 'Group'
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)
Found more than 10 errors and more than one error per 10 records, interrupted to avoid showing too many errors." while evaluating
'records.button_immediate_install()'

![Screenshot from 2022-01-24 00-51-43](https://user-images.githubusercontent.com/38361760/150719240-dbfb1fca-2e9b-4e89-89c5-963855bac40b.png)
`

**Comment by sfeilmeier** [comment]
Thank you for your interest. I updated the Odoo module to version 14 and fixed the incompatibilities with latest OpenEMS (https://github.com/OpenEMS/openems/pull/1822)

Please find the OpenEMS Gitpod Live-Demo for an integrated workspace with OpenEMS and Odoo
- https://openems.github.io/openems.io/openems/latest/simulation/gitpod.html
- https://gitpod.io/#https://github.com/OpenEMS/openems/tree/develop (only this link is working for now, till the next release on 1st June 2022)
