### ISSUE TITLE
Issue while adding User to "Alerting" Tab

### ISSUE THREAD

**Issue by Sn0w3y** [OpenEMS/odoo-openems#14]
If one tries to Add a User to an Edge Device onto the "Alerting" Tab sometimes an "Validation Error" can occur.

I have not found out the Root cause of it if I am honest because it appears only on one device right now but i guess we need to look into that.

If ONE Owner is in "Security" Tab and we try to include him into "Alerting" Tab everything is fine.

As soon as we try to add a second "Owner" Role to the Security Tab also everything is fine. But if we try to add the second owner to the "Alertings" Tab we get a ValidationError:

`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo16/odoo16/odoo/models.py", line 5172, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo16/odoo16/odoo/http.py", line 1591, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo16/odoo16/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo16/odoo16/odoo/http.py", line 1618, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo16/odoo16/odoo/http.py", line 1822, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo16/odoo16/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo16/odoo16/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo16/odoo16/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo16/odoo16/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo16/odoo16/odoo/api.py", line 469, in call_kw
    model.env.flush_all()
  File "/opt/odoo16/odoo16/odoo/api.py", line 744, in flush_all
    self._recompute_all()
  File "/opt/odoo16/odoo16/odoo/api.py", line 740, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/opt/odoo16/odoo16/odoo/models.py", line 6239, in _recompute_field
    field.recompute(records)
  File "/opt/odoo16/odoo16/odoo/fields.py", line 1370, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/opt/odoo16/odoo16/odoo/fields.py", line 1343, in apply_except_missing
    func(records)
  File "/opt/odoo16/odoo16/odoo/fields.py", line 1392, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo16/odoo16/odoo/models.py", line 4232, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo16/odoo16/odoo/fields.py", line 98, in determine
    return needle(*args)
  File "/opt/odoo16/odoo16/custom/openems/models/device.py", line 380, in _compute_user_role
  File "/opt/odoo16/odoo16/odoo/fields.py", line 1154, in __get__
    record.ensure_one()
  File "/opt/odoo16/odoo16/odoo/models.py", line 5175, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: openems.device_user_role(31, 33)

The above server error caused the following client error:
null`

**Comment by Sn0w3y** [comment]
Some News @da-Kai ?
